name:                NOAA-json
version:             0.1.0.0
github:              "Francososa/NOAA-json"
license:             BSD3
author:              "Francisco Sosa"
maintainer:          "franky.sosa@gmail.com"
copyright:           "Copyright (c) 2018 Francisco Sosa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            tests

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Francososa/NOAA-json#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  NOAA-json-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NOAA-json

tests:
  NOAA-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NOAA-json
